Aim for warningless (and more complete) test coverage on rebar3 and mix
erlef/setup-beam pull request #25
Opened 2021-03-30 18:14 UTC by paulo-ferraz-oliveira

Closes #23.

2021-03-30 20:52 UTC, paulo-ferraz-oliveira commented
A `mix` update seems to have sufficed for getting rid of the warnings.

2021-03-30 22:14 UTC, starbelly requested changes

2021-03-30 22:47 UTC, paulo-ferraz-oliveira commented on test-projects/mix/mix.lock
> +  "logfmt": {:hex, :logfmt, "3.3.1", "d9eaf344f81f4b4a6f2a1c73d79cb9cb4c4ff1d7c878d7a1bf3cb92761f653db", [:mix], [], "hexpm", "5030c9dafe1ef85e416cc867cd8db836de512c54047735c7a3e7be0ba67a532e"},
Hm... I'd initially pulled `jason` but then figured an update to `logfmt` did what I wanted (get rid of warnings). Apparently the lock file got "locked" with `jason`, even after a `mix deps.get`.

2021-03-30 22:51 UTC, starbelly commented on test-projects/mix/mix.lock
> +  "logfmt": {:hex, :logfmt, "3.3.1", "d9eaf344f81f4b4a6f2a1c73d79cb9cb4c4ff1d7c878d7a1bf3cb92761f653db", [:mix], [], "hexpm", "5030c9dafe1ef85e416cc867cd8db836de512c54047735c7a3e7be0ba67a532e"},
@paulo-ferraz-oliveira I think pulling it in is enough. Also, if you want to remove `jason` you need to `mix deps.unlock jason`

2021-03-30 22:54 UTC, paulo-ferraz-oliveira commented on test-projects/mix/mix.lock
> +  "logfmt": {:hex, :logfmt, "3.3.1", "d9eaf344f81f4b4a6f2a1c73d79cb9cb4c4ff1d7c878d7a1bf3cb92761f653db", [:mix], [], "hexpm", "5030c9dafe1ef85e416cc867cd8db836de512c54047735c7a3e7be0ba67a532e"},
`verl`'s now added to the mix.

2021-03-31 09:15 UTC, ericmj approved these changes

2021-03-31 17:45 UTC, paulo-ferraz-oliveira commented
I'm rebasing on top of `main` and force-pushing to be able to merge.

2021-03-31 17:52 UTC, merged